name: Bug Report
description: File a bug report.
title: '[Bug]: '
labels: ['bug', 'triage']
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report! Please follow the prompts below.
    - type: dropdown
      id: app
      attributes:
          label: Application
          description: Which application did you encounter the bug in?
          options:
              - Web App
              - iOS App
              - Android App
    - type: input
      id: contact
      attributes:
          label: Contact Details
          description: How can we get in touch with you if we need more info?
          placeholder: ex. email@example.com or nostr npub.
      validations:
          required: false
    - type: textarea
      id: what-happened
      attributes:
          label: What happened?
          description: Please describe the bug in detail, including the steps to reproduce the issue.
          placeholder: 'Describe the bug here...'
          value: |
              **Describe the bug:**  
              A clear and concise description of what the bug is.

              **To Reproduce:**  
              Steps to reproduce the behavior:
              1. Go to '...'
              2. Click on '...'
              3. Scroll down to '...'
              4. See error

              **What did you expect to happen?**  
              A clear and concise description of what you expected to happen.
      validations:
          required: true
    - type: input
      id: app_version
      attributes:
          label: Application Version
          description: 'What version of our app are you using? (e.g., the deployed version for the Web App or the app version for iOS/Android)'
          placeholder: 'e.g., 0.2.0'
      validations:
          required: true
    - type: input
      id: os_version
      attributes:
          label: OS Version
          description: Provide the version of your operating system (e.g., Windows 10, macOS 12.3).
          placeholder: e.g. Windows 10, macOS 12.3
      validations:
          required: true
    - type: input
      id: browser_version
      attributes:
          label: Browser Version (Optional for Web App)
          description: Provide your browser version if applicable (e.g., Chrome 89).
          placeholder: e.g. Chrome 89
      validations:
          required: false
    - type: textarea
      id: additinal context
      attributes:
          label: Additinal Context
          description: Any additinal detials that don't fit in the above cateogries that might be helpufl
    - type: textarea
      id: screenshots
      attributes:
          label: Screenshots
          description: Please attach screenshots of the bug if available. You can drag and drop images directly into this field or provide image URLs.
